<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CareBears</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/purecss@3.0.0/build/pure-min.css"
        integrity="sha384-X38yfunGUhNzHpBaEBsWLO+A0HDYOQi8ufWDkZ0k9e0eXz/tH3II7uKZ9msv++Ls" crossorigin="anonymous">
    <link rel="stylesheet" href="/style.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/purecss@3.0.0/build/grids-responsive-min.css">
</head>

<body>
    <div class="header">
        <div class="home-menu pure-menu pure-menu-horizontal pure-menu-fixed">
            <a class="pure-menu-heading" href=""><img src="/logo.jpeg" alt="Carebears Logo" class="logo"></a>


            <ul class="pure-menu-list">
                <li class="pure-menu-item"><a href="/characters/" class="pure-menu-link">Home</a></li>
                <li class="pure-menu-item"><a href="/characters/details/1" class="pure-menu-link">Details</a></li>
                <li class="pure-menu-item"><a href="/characters/about" class="pure-menu-link">About</a></li>
                <li class="pure-menu-item"><a href="/characters/add" class="pure-menu-link">Add new Character</a>
                </li>
                <!--Search -->
                <li class="pure-menu-item">
                    <form class="pure-form">
                        <input class="pure-input-rounded" type="search" placeholder="Search" />
                    </form>
                </li>
            </ul>
        </div>
    </div>

    <img src="/bear-banner.jpg" alt="Carebears" class="about-img">
    <div class="content" style="margin-top: 20px; padding: 20px;">
        <h1>About this project</h1>
        <p> I chose this theme because it was my favorite childhood show. I recently showed the show to my little sister
            and realized how much joy it brought me. The Carebears' message of kindness and caring resonates with me
            deeply, and I wanted to create a website that would kind of showcase this. </p>
        <h1>Design choices</h1>
        <p> I wanted to design this website to be minimal and easy to navigate, while still being visually appealing and
            informative. I sort of modeled the home page after pokemon playing cards with the way you have different
            "cards" laid out, an image in the center, and a quick description at the bottom. The details page was
            designed to be a bit more detailed but still trying to keep words to a minimum. </p>


</body>

</html>